#!/usr/bin/env python3
"""visual_audit.py — cc#2007/cc#2012 VISUAL_AUDIT_HARNESS_V1 + PIXEL LENS

cc#2007 built the MEASUREMENTS (five automated checks, PASS/FAIL rows). cc#2012 (founder ruling
12-Sep-2026 ~13:30 IST) adds the PICTURE: "Fable takes the full design and audit view of the app...
builds whatever it takes." As shipped under cc#2007, images were write-only -- a cron container's
own disk, discarded when the container exited, `image_path` a string nobody could open. Fable's own
web fetch reaches scorr.in (this CC container cannot), so a SERVED image is a real eye; a file path
into a container filesystem is not. This push moves the picture into Postgres and serves it.

WHAT CHANGED, cc#2012
    - Screenshots are JPEG (quality 80, not PNG) and captured as BYTES (`page.screenshot()` with no
      `path=` returns the bytes directly -- no more per-run shots directory at all).
    - Every capture's image is written to `visual_audit_captures.image_bytes`/`image_mime`, pass or
      fail alike -- this SUPERSEDES cc#2007/cc#2009's "image only on FAIL" storage revision, per the
      founder's own words. Retention (`_apply_retention`, below) keeps the LATEST capture per
      (route, theme, viewport) indefinitely, keeps a FAILING capture's image for 7 days after a newer
      one supersedes it, and nulls the bytes (never the row -- measurements/hash/status stay queryable
      forever) on everything else.
    - This is no longer a one-shot CLI script. `main()` is now a persistent WORKER loop (item 4):
      every 60s it drains `visual_audit_requests` (an on-demand capture queue -- item 5's `actions`
      let a request click through to a popup/modal state before the shot) and checks whether today's
      03:00 IST full crawl has already run, computed IN-PROCESS with a real Asia/Kolkata clock --
      NOT Railway cron, which is UTC-only and would have fired this at 08:30 IST, mid-morning, not
      overnight. Exits only on a fatal error; the Railway restart policy (railway.visualaudit.json)
      handles the rest. The Dockerfile's own CMD is unchanged (`python3 visual_audit.py`) -- only what
      happens after that command starts is different.
    - Serving lives in visual_audit_endpoints.py: two NEW routes, `GET .../capture/{id}` and
      `GET .../runs/latest`, gated by a single query-param token compared constant-time against
      `VISUAL_AUDIT_VIEW_TOKEN` (web-service env, never generated by CC, never in this repo or any
      log) -- wrong or missing token is a 404, not a 401, and an unset env var means every request to
      either route 404s, fail-closed. The existing `/api/visual-audit/failures` (cc#2007) is
      untouched, per do_not_touch.

WHAT DID NOT CHANGE, cc#2007's own original notes below still apply
    This is the LIVE-SITE counterpart to tools/render_check.py (cc#1133 "CC EYES"), which renders
    the repo TEMPLATE standalone and says so in its own docstring: "There is no route to scorr.in
    from the CC container." This module runs as its own process against a REAL deployed instance,
    logged in as a real session. It launches Playwright's own bundled browser (cc#2014: no default executable_path;
    CC_CHROMIUM is an optional override only) and reuses render_check.py's proven
    overflow/clipping DOM-probe logic (credited inline in CHECKS_JS) rather than re-deriving it.

    do_not_touch item 1 (cc#2007's own words, still true under cc#2012): "this job must not run
    inside [the web process] or add latency to any user request." So this still does NOT register
    as a category='scheduler_loop' row and is NOT dispatched by scheduler.py's own tick loop --
    scheduler_master.py's `_WORKER_JOBS` hand-entered list (the same mechanism worker/fyers_feed.py's
    own in-process loops use, for the identical reason: an in-process while-loop is invisible to the
    AST-derived scheduler-loop enumerator) is what keeps cc#759's drift audit from re-retiring this
    row now that it is a real in-process worker rather than a cron-fired script.

    do_not_touch item 1 also names worker/**: this file is deliberately NOT under worker/ -- that
    tree bounces the fyers feed service on every change (FEED WORKER DEPLOY RULE, cc#416); a file
    living there would make an unrelated visual-audit change trigger a feed-worker redeploy for no
    reason.

ITEM 7 (THEME LEAK) — WHAT "REUSE THEIR TOKEN REGISTRY, DO NOT BUILD A SECOND ONE" MEANS HERE
    (unchanged from cc#2007) Read theme_validator.py before touching this: its registry is a
    STATIC-SOURCE scan (raw_literals/count_raw parse stylesheet TEXT for var(--x, #literal) and bare
    literals) -- it has no browser and never renders a page, which is exactly why cc#1941/cc#1970 (a
    JS-appended overlay landing outside every CSS scope, so its OWN correct-looking var() names
    resolved to nothing) were invisible to it for months. That check already runs as its own push
    gate -- duplicating it here would be the "build a second one" cc#2007 said not to do. The
    theme_leak check below measures a RENDERED element's own inverted background luminance, the
    thing a static scanner structurally cannot see; it does not re-flag literal-colour source lines.

VERIFY STATE (cc#2012 push) — read before trusting a "first run"
    Structural, this container's own sandbox: JPEG-bytes capture, the retention/purge SQL, the
    actions executor (click/wait_ms) and the token check all exercised for real against synthetic
    data -- see reports/CC2012_visual_audit_pixel_lens.md for the exact commands and output.
    NOT done, and cannot be done from here: the persistent worker LOOP itself (60s poll, the daily
    IST-clock trigger) running for real, and the actual deployed capture -- this container has no
    route to scorr.in and the ALTER TABLE this card needs (image_bytes/image_mime/has_check_fail on
    visual_audit_captures) is BLOCKED by MAINTENANCE_LOCK_RULE (cc#351) on the run_sql path; it is
    proposed, not applied, in the report. Built-and-registered is not live (rule 9) -- stated
    plainly, with the exact remaining steps named rather than assumed done.
"""

import argparse
import hashlib
import json
import logging
import os
import re
import sys
import time
import uuid
from datetime import date, datetime, timezone
from zoneinfo import ZoneInfo

import psycopg

IST = ZoneInfo("Asia/Kolkata")
MAX_ACTION_STEPS = 10

log = logging.getLogger("scorr.visual_audit")

DATABASE_URL = os.environ.get("DATABASE_URL")
# cc#2014: NO default browser path. Inside the official Playwright image the library resolves its
# own bundled browser (v1.48.0-jammy ships chromium revision 1140 -- read from the wheel's
# browsers.json, not guessed); the old hardcoded chromium-1194 path was copied from CC's own
# container, did not exist in the image, and made launch() raise before login on every boot.
# CC_CHROMIUM is an OPTIONAL override only: executable_path is passed to launch() if and only if
# the env var is explicitly set. Leave it unset on the Railway service.
CHROME = os.environ.get("CC_CHROMIUM") or None
# cc#2012: no SHOTS_DIR any more -- images go to Postgres as bytes, never to the container's disk.

# item 4: representative dark + light set, both confirmed COMPLETE (theme_validate, 12-Sep) —
# see the module docstring for why these two specifically.
THEMES = ["goldnight", "aquawhite"]
# item 4: mobile viewport matches tools/render_check.py's own Android reference width (412) rather
# than inventing a third convention; desktop is a common 16:10 laptop size.
VIEWPORTS = [("mobile", 412, 915), ("desktop", 1440, 900)]

CONTRAST_BODY_MIN = 4.5
CONTRAST_LARGE_MIN = 3.0
TAP_TARGET_MIN_PX = 44
ERROR_STRINGS = ["undefined", "NaN", "[object Object]", "Could not load", "could not load",
                 "Error:", "TypeError", "ReferenceError", "500 Internal", "Traceback"]


def _conn():
    return psycopg.connect(DATABASE_URL)


# ---------------------------------------------------------------------------
# Item 3: route enumeration, REGISTRY-DERIVED from the live NAV array source.
# ---------------------------------------------------------------------------

_JS_ESC_RE = re.compile(r"\\u([0-9a-fA-F]{4})|\\(.)")


def _unescape_layer(s):
    return _JS_ESC_RE.sub(lambda m: chr(int(m.group(1), 16)) if m.group(1) else m.group(2), s)


def _js_unescape(s):
    """Decode a NAV entry field to the text the nav actually RENDERS, not the source bytes. The NAV
    array sits inside `PWA_JS = \"\"\"...\"\"\"` -- a NON-raw Python string -- so the bytes on disk
    carry two escape layers: Python's (`\\\\u00b7` -> `\\u00b7`) and then the JS literal's
    (`\\u00b7` -> `·`). One pass per layer, in that order. app_route_map stores the rendered text
    ('V9 · Pairs'), and the upsert must match it rather than rewrite it back to an escape."""
    return _unescape_layer(_unescape_layer(s))


def parse_nav_routes(pwa_endpoints_path="pwa_endpoints.py"):
    """Extract every [path, icon, label(, flag)] entry from pwa_endpoints.py's own `var NAV = [...]`
    block. Never a hardcoded page list (item 3) -- reads the live source file fresh on every call,
    so a NAV edit is picked up on the crawler's next run with no change needed here. Depth-scanned
    rather than regex-bounded, because the block runs hundreds of lines with nested `//` comments
    that can themselves contain brackets (see the comment text throughout that array today) -- a
    naive "first `];`" regex would stop at the first comment that happens to contain one."""
    src = open(pwa_endpoints_path, encoding="utf-8").read()
    m = re.search(r"var\s+NAV\s*=\s*\[", src)
    if not m:
        raise RuntimeError(f"could not find 'var NAV = [' in {pwa_endpoints_path} -- "
                            "the live nav source has moved or been renamed; STOP, do not guess")
    start = m.end() - 1  # position of the opening '['
    depth = 0
    end = None
    for i in range(start, len(src)):
        c = src[i]
        if c == '[':
            depth += 1
        elif c == ']':
            depth -= 1
            if depth == 0:
                end = i
                break
    if end is None:
        raise RuntimeError(f"unbalanced brackets scanning the NAV array in {pwa_endpoints_path}")
    block = src[start:end + 1]
    entry_re = re.compile(r"\[\s*'((?:[^'\\]|\\.)*)'\s*,\s*'((?:[^'\\]|\\.)*)'\s*,"
                           r"\s*'((?:[^'\\]|\\.)*)'(?:\s*,\s*'((?:[^'\\]|\\.)*)')?\s*\]")
    routes = []
    for em in entry_re.finditer(block):
        path, icon, label, flag = (_js_unescape(g) if g is not None else None for g in em.groups())
        routes.append({"path": path, "icon": icon, "label": label, "flag": flag})
    # de-dupe on path -- the array should not repeat one (rule 8), but a crawler must not silently
    # capture the same route twice and call it two routes if it ever does.
    seen, deduped = set(), []
    for r in routes:
        if r["path"] in seen:
            continue
        seen.add(r["path"])
        deduped.append(r)
    return deduped


# ---------------------------------------------------------------------------
# Item 2: login. ONE shared site password (scorr_auth.py), not a per-service account -- driven as a
# real browser interaction (find the password input by TYPE, not by its randomized per-load NAME,
# per scorr_auth.py's own anti-autofill comment) rather than reverse-engineering the POST body.
# ---------------------------------------------------------------------------

def login(page, base_url, password):
    page.goto(base_url.rstrip("/") + "/login", wait_until="domcontentloaded")
    page.locator('input[type=password]').first.fill(password)
    page.locator('button[type=submit]').first.click()
    page.wait_for_load_state("domcontentloaded")
    cookie = [c for c in page.context.cookies() if c["name"] == "scorr_auth"]
    if not cookie:
        raise RuntimeError("login did not produce a scorr_auth cookie -- wrong password, or the "
                            "login form changed shape. STOP per the card's own gate: do not "
                            "capture only whatever public pages happen to be reachable and call "
                            "that full coverage.")


# ---------------------------------------------------------------------------
# Items 6-10: the five automated checks. Each runs inside the page and returns a list of
# {check, status, selector, measured, expected, detail} dicts -- PASS rows are included
# deliberately (item 11: "One row per check per element", not "one row per FAILURE").
# ---------------------------------------------------------------------------

CHECKS_JS = r"""
() => {
  const out = [];
  const sel = (el) => {
    if (!el) return '?';
    let s = el.tagName.toLowerCase();
    if (el.id) return s + '#' + el.id;
    const c = (el.className && el.className.baseVal !== undefined) ? el.className.baseVal : (el.className || '');
    if (typeof c === 'string' && c.trim()) s += '.' + c.trim().split(/\s+/).slice(0, 3).join('.');
    return s;
  };
  const hiddenByAncestor = (el) => {
    // credit: tools/render_check.py (cc#1133) PROBE's own hiddenByAncestor -- a closed overlay is
    // not a layout defect, and that tool already learned this the hard way (its own comment).
    for (let p = el; p && p !== document.documentElement; p = p.parentElement) {
      const cs = getComputedStyle(p);
      if (cs.display === 'none' || cs.visibility === 'hidden' || +cs.opacity === 0) return true;
    }
    return false;
  };
  const vis = (el) => {
    if (hiddenByAncestor(el)) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  };
  const push = (check, status, el, measured, expected, detail) => {
    out.push({ check, status, selector: sel(el), measured: String(measured), expected: String(expected), detail: detail || '' });
  };

  // ---- shared: effective (non-transparent) background, walking up the tree ----
  const parseRgba = (s) => {
    const m = /rgba?\(([^)]+)\)/.exec(s || '');
    if (!m) return null;
    const parts = m[1].split(',').map(x => parseFloat(x.trim()));
    return { r: parts[0], g: parts[1], b: parts[2], a: parts.length > 3 ? parts[3] : 1 };
  };
  const effectiveBg = (el) => {
    for (let p = el; p; p = p.parentElement) {
      const c = parseRgba(getComputedStyle(p).backgroundColor);
      if (c && c.a > 0.01) return c;
      if (p === document.documentElement) break;
    }
    return { r: 255, g: 255, b: 255, a: 1 };  // CSS canvas default
  };
  const luminance = (c) => {
    const f = (v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); };
    return 0.2126 * f(c.r) + 0.7152 * f(c.g) + 0.0722 * f(c.b);
  };
  const contrastRatio = (c1, c2) => {
    const l1 = luminance(c1) + 0.05, l2 = luminance(c2) + 0.05;
    return l1 > l2 ? l1 / l2 : l2 / l1;
  };

  // ---- text-bearing leaves, same definition render_check.py (cc#1133) uses ----
  const leaves = [...document.body.querySelectorAll('*')].filter(el => {
    if (/^(script|style|svg|path|line|rect|circle|polyline|br|head|meta|link)$/i.test(el.tagName)) return false;
    if (!vis(el)) return false;
    if (![...el.childNodes].some(n => n.nodeType === 3 && n.textContent.trim())) return false;
    return true;
  });

  // ==== 6. CONTRAST ====
  for (const el of leaves) {
    const cs = getComputedStyle(el);
    const fg = parseRgba(cs.color);
    if (!fg) continue;
    const bg = effectiveBg(el);
    const ratio = contrastRatio(fg, bg);
    const px = parseFloat(cs.fontSize) || 0;
    const bold = (parseInt(cs.fontWeight, 10) || 400) >= 700;
    const isLarge = px >= 24 || (px >= 18.66 && bold);
    const need = isLarge ? 3.0 : 4.5;
    const status = ratio >= need ? 'PASS' : 'FAIL';
    push('contrast', status, el, ratio.toFixed(2) + ':1', need.toFixed(1) + ':1',
         (isLarge ? 'large text' : 'body text') + ` fg rgb(${fg.r},${fg.g},${fg.b}) on effective bg rgb(${bg.r},${bg.g},${bg.b})`);
  }

  // ==== 7. THEME LEAK (runtime signal only -- see module docstring for why) ====
  const theme = document.body.getAttribute('data-theme') || '';
  const bodyBg = parseRgba(getComputedStyle(document.body).backgroundColor) || { r: 255, g: 255, b: 255, a: 1 };
  const pageIsDark = luminance(bodyBg) < 0.4;
  const bigEls = [...document.body.querySelectorAll('*')].filter(el => {
    if (!vis(el)) return false;
    const r = el.getBoundingClientRect();
    return r.width >= 80 && r.height >= 40;  // skip small chips/dots -- a founder-visible surface, not a pixel
  });
  const seenBoxes = [];
  for (const el of bigEls) {
    const c = parseRgba(getComputedStyle(el).backgroundColor);
    if (!c || c.a < 0.5) continue;  // only an element that actually PAINTS a background of its own
    const lum = luminance(c);
    const inverted = pageIsDark ? lum > 0.75 : lum < 0.15;
    if (!inverted) continue;
    const r = el.getBoundingClientRect();
    const key = Math.round(r.left) + ',' + Math.round(r.top) + ',' + Math.round(r.width);
    if (seenBoxes.includes(key)) continue;  // a parent and its full-bleed child both painting are one finding, not two
    seenBoxes.push(key);
    push('theme_leak', 'FAIL', el, `bg rgb(${c.r},${c.g},${c.b}) lum=${lum.toFixed(2)}`,
         `consistent with data-theme="${theme}" (page lum=${luminance(bodyBg).toFixed(2)})`,
         'element background luminance is inverted against the page\'s own active theme -- the black-popup-on-white-theme class');
  }
  if (!seenBoxes.length) push('theme_leak', 'PASS', document.body, `page lum=${luminance(bodyBg).toFixed(2)}`, `data-theme="${theme}"`, 'no inverted-background element found');

  // ==== 8. OVERFLOW AND CLIPPING ====
  const de = document.documentElement;
  const docOverflow = de.scrollWidth - de.clientWidth;
  push('overflow_clipping', docOverflow > 1 ? 'FAIL' : 'PASS', de, docOverflow + 'px', '<=1px', 'document horizontal scroll');
  for (const el of document.body.querySelectorAll('*')) {
    if (!vis(el)) continue;
    const cs = getComputedStyle(el);
    const excess = el.scrollWidth - el.clientWidth;
    if (excess > 2 && !/auto|scroll/.test(cs.overflowX)) {
      const kids = [...el.children].filter(k => (k.textContent || '').trim());
      if (kids.length) push('overflow_clipping', 'FAIL', el, excess + 'px', '0px (or a scrollable container)', 'content clipped, no way to scroll to it');
    }
    const r = el.getBoundingClientRect();
    if (r.width > 0 && r.right > window.innerWidth + 2 && cs.position !== 'fixed') {
      push('overflow_clipping', 'FAIL', el, Math.round(r.right) + 'px', window.innerWidth + 'px (viewport width)', 'element extends past the right edge of the viewport');
    }
  }

  // ==== 9. TAP TARGETS ====
  const interactive = document.body.querySelectorAll('button, a[href], [onclick], [role="button"], input, select, textarea');
  for (const el of interactive) {
    if (!vis(el)) continue;
    const r = el.getBoundingClientRect();
    const status = (r.width >= 44 && r.height >= 44) ? 'PASS' : 'FAIL';
    push('tap_target', status, el, Math.round(r.width) + 'x' + Math.round(r.height) + 'px', '44x44px', '');
  }

  // ==== 10. EMPTY AND BROKEN ====
  const bodyText = document.body.innerText || '';
  let anyErrorString = false;
  for (const needle of window.__CC_ERROR_STRINGS__ || []) {
    if (bodyText.indexOf(needle) === -1) continue;
    anyErrorString = true;
    push('empty_broken', 'FAIL', document.body, 'contains "' + needle + '"', 'no error string visible', 'a visible error string survived to render');
  }
  if (!anyErrorString) push('empty_broken', 'PASS', document.body, 'no known error string found', 'no error string visible', '');
  // a content-shaped container (this codebase's own .card/.c/.sect/.oib families, seen throughout
  // this session) that occupies real space but paints no text at all -- a placeholder or a section
  // that silently rendered nothing. Heuristic, stated as such: not every empty container is a bug
  // (e.g. a genuinely empty state already renders its OWN "nothing here" text, which is why this
  // only fires on TRULY empty -- zero characters, not "renders an honest empty-state sentence").
  const containerSel = '.card, .c, .sect, .oib, .vpage, .oic, .deriv-row, .apf-note';
  for (const el of document.body.querySelectorAll(containerSel)) {
    if (!vis(el)) continue;
    const r = el.getBoundingClientRect();
    if (r.width < 20 || r.height < 20) continue;
    const text = (el.innerText || '').trim();
    if (text.length === 0) push('empty_broken', 'FAIL', el, '0 characters of text', '>0 characters, or an explicit empty-state message', 'content container rendered with no text at all');
  }

  return out;
}
"""


def run_checks(page):
    page.evaluate("window.__CC_ERROR_STRINGS__ = %s" % json.dumps(ERROR_STRINGS))
    return page.evaluate(CHECKS_JS)


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def execute_actions(page, actions):
    """cc#2012 item 5: a request row's `actions` -- a JSON list of {"click": "<selector>"} and
    {"wait_ms": N} steps, run after load and before the capture, so a popup, a modal or a tab state
    can be photographed (the black-popup-on-light-theme class lives behind a tap). BOUNDED by design:
    at most MAX_ACTION_STEPS, only these two step shapes, selector strings only -- there is no path
    here that evaluates arbitrary JS, and an unrecognised step is skipped, never executed."""
    if not actions or not isinstance(actions, list):
        return 0
    ran = 0
    for step in actions[:MAX_ACTION_STEPS]:
        if not isinstance(step, dict):
            continue
        if "click" in step and isinstance(step["click"], str) and step["click"].strip():
            page.locator(step["click"]).first.click(timeout=5000)
            ran += 1
        elif "wait_ms" in step:
            page.wait_for_timeout(max(0, min(int(step["wait_ms"]), 10000)))  # cap a single wait at 10s
            ran += 1
    return ran


def capture_one(page, base_url, route_path, theme, viewport_name, width, height, actions=None):
    """One route x theme x viewport: navigate, settle, run any requested actions, then take the
    JPEG and the five checks. Returns the image BYTES (cc#2012 item 1: JPEG quality 80, ~60-120KB
    each, captured for EVERY capture pass or fail -- the founder's storage revision that limited the
    image to failures is superseded by cc#2012's own spec_source). `page.screenshot()` with no path
    returns bytes -- nothing is written to the container's disk any more, which is the whole point:
    that disk was the write-only trap cc#2012 exists to fix."""
    page.set_viewport_size({"width": width, "height": height})
    sep = "&" if "?" in route_path else "?"
    url = base_url.rstrip("/") + route_path + sep + "theme=" + theme
    result = {"route": route_path, "theme": theme, "viewport": viewport_name,
              "status": "ok", "error": None, "checks": [], "content_hash": None,
              "image_bytes": None, "image_mime": None, "actions_ran": 0}
    try:
        page.goto(url, wait_until="domcontentloaded", timeout=20000)
        try:
            page.wait_for_load_state("networkidle", timeout=8000)
        except Exception:
            pass  # a page with a long-poll/live connection never goes idle -- proceed on what rendered
        page.wait_for_timeout(500)  # settle: async paints (cc#1133's own "settle_ms" precedent)
        result["actions_ran"] = execute_actions(page, actions)
        if result["actions_ran"]:
            page.wait_for_timeout(300)  # let whatever the action opened finish painting
        html = page.content()
        result["content_hash"] = hashlib.sha256(html.encode("utf-8", "ignore")).hexdigest()[:16]
        result["image_bytes"] = page.screenshot(type="jpeg", quality=80, full_page=True)
        result["image_mime"] = "image/jpeg"
        result["checks"] = run_checks(page)
    except Exception as e:
        result["status"] = "error"
        result["error"] = f"{type(e).__name__}: {str(e)[:300]}"
    return result


def _write_capture(cur, run_id, cap):
    """Write one capture row + its check rows, then apply retention for its (route, theme,
    viewport) combo. Returns (capture_id, has_fail). Shared by the daily crawl and the on-demand
    request path so both write identically -- one writer, not two."""
    has_fail = cap["status"] == "error" or any(c["status"] == "FAIL" for c in cap["checks"])
    cur.execute(
        """INSERT INTO visual_audit_captures
           (run_id, route, theme, viewport, content_hash, image_bytes, image_mime, has_check_fail, status, error)
           VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id""",
        (run_id, cap["route"], cap["theme"], cap["viewport"], cap["content_hash"],
         cap["image_bytes"], cap["image_mime"], has_fail, cap["status"], cap["error"]))
    capture_id = cur.fetchone()[0]
    for c in cap["checks"]:
        cur.execute(
            """INSERT INTO visual_audit_results
               (run_id, capture_id, route, theme, viewport, check_name, status, selector, measured, expected, detail)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
            (run_id, capture_id, cap["route"], cap["theme"], cap["viewport"],
             c["check"], c["status"], c["selector"], c["measured"], c["expected"], c["detail"]))
    _apply_retention(cur, cap["route"], cap["theme"], cap["viewport"], capture_id)
    return capture_id, has_fail


def _apply_retention(cur, route, theme, viewport, keep_id):
    """cc#2012 item 1 retention, per (route, theme, viewport) combo: the row just written (keep_id)
    is the LATEST and its bytes are kept indefinitely -- it is excluded from this UPDATE entirely.
    Every OLDER row of the SAME combo keeps its bytes only if it recorded a check FAIL and is still
    within 7 days; everything else has its bytes nulled. The ROW itself is never deleted here --
    measurements, hash and status stay queryable forever, exactly cc#2007's own "PASS and FAIL
    rows both kept, only the image is conditional" principle, now applied per-combo rather than
    per-run. `has_check_fail` is a column on the captures row (set at insert) so this is one
    index-friendly statement, not a per-row join against visual_audit_results."""
    cur.execute(
        """UPDATE visual_audit_captures
           SET image_bytes = NULL, image_mime = NULL
           WHERE route = %s AND theme = %s AND viewport = %s AND id <> %s
             AND image_bytes IS NOT NULL
             AND NOT (has_check_fail AND captured_at >= now() - interval '7 days')""",
        (route, theme, viewport, keep_id))


def _viewport(name):
    for vp_name, w, h in VIEWPORTS:
        if vp_name == name:
            return vp_name, w, h
    raise ValueError(f"unknown viewport '{name}' -- one of {[v[0] for v in VIEWPORTS]}")


def _record_run(conn, status, error=None, duration_ms=None):
    """Update the scheduler_master row this worker is registered under (ENGINE_LIVENESS_RULE 13829:
    last_run_at is the liveness evidence, the badge follows the data). Never raises -- a registry
    write failing must not take the crawl down with it."""
    try:
        with conn.cursor() as cur:
            cur.execute("""UPDATE scheduler_master SET last_run_at=NOW(), last_status=%s, last_error=%s,
                           last_duration_ms=%s WHERE job_name='visual_audit_crawl'""",
                        (status, (error or None) and str(error)[:500], duration_ms))
        conn.commit()
    except Exception as e:
        log.warning("scheduler_master record_run failed: %s", e)


ROUTE_MAP_UNMAPPED = "unmapped"


def sync_route_map(conn, routes, run_id):
    """Fable's addendum on cc#2012 (cc_task_logs 6427): at the start of every full crawl, upsert
    app_route_map from the SAME parse_nav_routes output the crawl walks, so the table can never
    drift from the live nav. Only what the NAV itself carries is written: route, label, nav_flag,
    nav_position, and surface (flag 'm' = mobile, anything else = web -- the exact split the table
    holds today). What only Fable knows -- route_group, serving_file, handler, template -- is NEVER
    overwritten: an existing row keeps its mapping untouched; a route new to the nav lands with the
    literal sentinel 'unmapped' in those columns plus a WARNING, so Fable fills it in rather than
    the crawler guessing a handler. Rows whose route has left the nav are NOT deleted (the table is
    Fable's) -- they are reported as stale in the return value and the log. Never raises: a map
    failure must not stop the crawl that follows it."""
    out = {"upserted": 0, "new": [], "stale": []}
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT route FROM app_route_map")
            existing = {r[0] for r in cur.fetchall()}
            nav_paths = []
            for pos, r in enumerate(routes, start=1):
                path = r["path"]
                nav_paths.append(path)
                if path not in existing:
                    out["new"].append(path)
                cur.execute(
                    """INSERT INTO app_route_map
                           (route, label, surface, nav_flag, route_group, serving_file, handler,
                            template, nav_position, source, added_by)
                       VALUES (%s, %s, %s, %s, %s, %s, %s, NULL, %s, %s, 'visual_audit')
                       ON CONFLICT (route) DO UPDATE SET
                           label = EXCLUDED.label,
                           surface = EXCLUDED.surface,
                           nav_flag = EXCLUDED.nav_flag,
                           nav_position = EXCLUDED.nav_position""",
                    (path, r["label"], "mobile" if r["flag"] == "m" else "web", r["flag"],
                     ROUTE_MAP_UNMAPPED, ROUTE_MAP_UNMAPPED, ROUTE_MAP_UNMAPPED, pos,
                     f"pwa_endpoints.py NAV array, visual_audit crawl {run_id}"))
                out["upserted"] += 1
            out["stale"] = sorted(existing - set(nav_paths))
        conn.commit()
        if out["new"]:
            log.warning("app_route_map: %d route(s) new to the nav, inserted as '%s' -- Fable to map: %s",
                        len(out["new"]), ROUTE_MAP_UNMAPPED, out["new"])
        if out["stale"]:
            log.warning("app_route_map: %d row(s) no longer in the live nav (left in place): %s",
                        len(out["stale"]), out["stale"])
    except Exception as e:
        try:
            conn.rollback()
        except Exception:
            pass
        out["error"] = f"{type(e).__name__}: {str(e)[:300]}"
        log.warning("app_route_map sync failed (crawl continues): %s", e)
    return out


def run_crawl(page, base_url, conn, routes=None, themes=None, viewports=None):
    """The FULL crawl: every NAV route x theme x viewport. Takes an already-logged-in page and an
    open connection (the worker owns both for its whole lifetime) rather than opening its own, so
    the daily crawl and the on-demand poller share one browser session and one login."""
    run_id = uuid.uuid4().hex[:16]
    routes = routes if routes is not None else parse_nav_routes()
    themes = themes or THEMES
    viewports = viewports or VIEWPORTS
    summary = {"run_id": run_id, "routes_enumerated": len(routes), "captures": 0,
               "checks_run": 0, "failures_by_check": {}, "worst_routes": {},
               "route_map": sync_route_map(conn, routes, run_id)}
    t0 = time.time()
    with conn.cursor() as cur:
        for route in routes:
            for theme in themes:
                for vp_name, w, h in viewports:
                    cap = capture_one(page, base_url, route["path"], theme, vp_name, w, h)
                    summary["captures"] += 1
                    _write_capture(cur, run_id, cap)
                    for c in cap["checks"]:
                        summary["checks_run"] += 1
                        if c["status"] == "FAIL":
                            summary["failures_by_check"][c["check"]] = summary["failures_by_check"].get(c["check"], 0) + 1
                            summary["worst_routes"][cap["route"]] = summary["worst_routes"].get(cap["route"], 0) + 1
                    conn.commit()
    summary["worst_routes"] = dict(sorted(summary["worst_routes"].items(), key=lambda kv: -kv[1])[:10])
    summary["duration_ms"] = int((time.time() - t0) * 1000)
    _record_run(conn, "ok", duration_ms=summary["duration_ms"])
    return summary


def process_requests(page, base_url, conn):
    """cc#2012 item 4(a): drain visual_audit_requests WHERE status='pending'. Each request is one
    capture (route, theme, viewport, optional actions) written through the SAME _write_capture the
    daily crawl uses, then the request row is set done+capture_id or error+message. Oldest first.
    A single bad request (unknown viewport, a selector that never appears) is recorded on ITS row
    and does not stop the rest of the queue."""
    with conn.cursor() as cur:
        cur.execute("""SELECT id, route, theme, viewport, actions FROM visual_audit_requests
                       WHERE status='pending' ORDER BY requested_at ASC LIMIT 20""")
        pending = cur.fetchall()
    done = 0
    for req_id, route, theme, viewport, actions in pending:
        try:
            with conn.cursor() as cur:
                cur.execute("UPDATE visual_audit_requests SET status='running', updated_at=now() WHERE id=%s", (req_id,))
            conn.commit()
            vp_name, w, h = _viewport(viewport)
            if theme not in THEMES:
                raise ValueError(f"unknown theme '{theme}' -- one of {THEMES}")
            if isinstance(actions, str):
                actions = json.loads(actions)
            cap = capture_one(page, base_url, route, theme, vp_name, w, h, actions=actions)
            with conn.cursor() as cur:
                capture_id, _ = _write_capture(cur, "req-" + uuid.uuid4().hex[:8], cap)
                if cap["status"] == "error":
                    cur.execute("""UPDATE visual_audit_requests SET status='error', error=%s, capture_id=%s,
                                   updated_at=now() WHERE id=%s""", (cap["error"], capture_id, req_id))
                else:
                    cur.execute("""UPDATE visual_audit_requests SET status='done', capture_id=%s, error=NULL,
                                   updated_at=now() WHERE id=%s""", (capture_id, req_id))
            conn.commit()
            done += 1
        except Exception as e:
            conn.rollback()
            try:
                with conn.cursor() as cur:
                    cur.execute("""UPDATE visual_audit_requests SET status='error', error=%s, updated_at=now()
                                   WHERE id=%s""", (f"{type(e).__name__}: {str(e)[:400]}", req_id))
                conn.commit()
            except Exception as e2:
                log.error("could not even record the error on request %s: %s", req_id, e2)
    return done


def daily_crawl_due(conn, now_ist=None):
    """cc#2012 item 4(b): the full crawl runs once a day at 03:00 IST, decided HERE with a real
    Asia/Kolkata clock -- not by Railway cron, which is UTC-only ('0 3 * * *' there is 08:30 IST,
    mid-session, the exact thing that must not happen). Due when: it is at or past 03:00 IST today
    AND scheduler_master.last_run_at (the registry's own liveness stamp) is not already from today
    in IST. A restart at 14:00 IST on a day the 03:00 run was missed therefore runs it once, then
    waits for tomorrow -- catches up, never double-runs."""
    now_ist = now_ist or datetime.now(IST)
    if now_ist.hour < 3:
        return False
    with conn.cursor() as cur:
        cur.execute("SELECT last_run_at FROM scheduler_master WHERE job_name='visual_audit_crawl'")
        row = cur.fetchone()
    last = row[0] if row else None
    if last is None:
        return True
    if last.tzinfo is None:
        last = last.replace(tzinfo=timezone.utc)
    return last.astimezone(IST).date() < now_ist.date()


def launch_browser(p):
    """cc#2014 item 2 -- boot-time preflight, BEFORE login. Launch the browser Playwright resolves
    itself (or CC_CHROMIUM if explicitly set), log the resolved browser version so the Deploy Logs
    prove the process got past the launch, and hand the browser back. If launch fails, log the
    reason and the path it tried at ERROR and exit non-zero -- the 12-Sep crash was visible only in
    Railway's Deploy Logs, with nothing in the app naming the cause. Raises SystemExit(1) on failure
    so Railway's ON_FAILURE restart policy takes over."""
    kwargs = {"headless": True}
    if CHROME:
        kwargs["executable_path"] = CHROME
    where = f"CC_CHROMIUM={CHROME}" if CHROME else "Playwright's bundled browser (no executable_path)"
    try:
        browser = p.chromium.launch(**kwargs)
    except Exception as e:
        log.error("browser launch FAILED using %s: %s: %s", where, type(e).__name__, str(e).strip()[:600])
        raise SystemExit(1)
    log.info("browser ready: chromium %s via %s", browser.version, where)
    return browser


def worker(base_url, password, poll_seconds=60, once=False):
    """The long-running process (cc#2012 item 4). One browser, one login, one DB connection, held
    for the life of the process. Every `poll_seconds`: drain pending on-demand requests, then run the
    daily crawl if it is due. Non-fatal errors (one request failing, a transient DB hiccup) are
    logged and the loop continues; a fatal error (login impossible, browser gone) propagates and the
    process exits so Railway's restart policy takes over. `once=True` runs a single iteration -- the
    manual-trigger / smoke-test path."""
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = launch_browser(p)       # cc#2014 preflight: logs the version, or exits non-zero
        context = browser.new_context()
        page = context.new_page()
        login(page, base_url, password)   # raises -> fatal -> exit, per cc#2007's own gate
        conn = _conn()
        try:
            while True:
                try:
                    n = process_requests(page, base_url, conn)
                    if n:
                        log.info("processed %d on-demand capture request(s)", n)
                    if daily_crawl_due(conn):
                        log.info("daily crawl due (IST) -- starting")
                        s = run_crawl(page, base_url, conn)
                        log.info("daily crawl done: %s", json.dumps(s))
                except psycopg.OperationalError as e:
                    log.warning("DB hiccup, reconnecting: %s", e)
                    try:
                        conn.close()
                    except Exception:
                        pass
                    conn = _conn()
                except Exception as e:
                    log.error("worker iteration failed (continuing): %s", e, exc_info=True)
                    try:
                        conn.rollback()
                    except Exception:
                        pass
                if once:
                    break
                time.sleep(poll_seconds)
        finally:
            conn.close()
            browser.close()


def main():
    ap = argparse.ArgumentParser(description="cc#2007/cc#2012 visual audit worker")
    ap.add_argument("--base-url", default=os.environ.get("VISUAL_AUDIT_BASE_URL", "http://127.0.0.1:8000"))
    ap.add_argument("--password", default=os.environ.get("SCORR_AUTH_PASSWORD", ""))
    ap.add_argument("--poll-seconds", type=int, default=int(os.environ.get("VISUAL_AUDIT_POLL_SECONDS", "60")))
    ap.add_argument("--once", action="store_true", help="one poll iteration (drain requests, crawl if due), then exit")
    a = ap.parse_args()
    if not a.password:
        print("SCORR_AUTH_PASSWORD not set -- cannot log in, per the card's own gate. STOP.", file=sys.stderr)
        return 1
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    worker(a.base_url, a.password, poll_seconds=max(5, a.poll_seconds), once=a.once)
    return 0


if __name__ == "__main__":
    sys.exit(main())
